version: "3"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/api
    networks:
      - host

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adm

networks:
  host:
    driver: bridge
